title: Python training bootcamp
author: Hive
email: mcsnootch@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A site to help facilitate a python learning day for teachers

twitter_username: mcsnootch
github_username:  mcsnootch

sass:
    style: compressed

highlighter: rouge
header_pages: Home, Tracks
